#!/bin/sh
#We don't understand the license things, so let it go.
#Please don't do evil to us.
#v2015-1-10 qizha/wangke/noel/summer
i=0
#echo "HTTP/1.1 200 OK"
echo "Content-Type: application/json"
echo ""
echo "{"
iwpriv ra0 set SiteSurvey=0
iwpriv ra0 get_site_survey | grep '^[0-9]' | while read line
do
	chanel=`echo $line | awk '{print $1}'`
	
	if [ "${line:4:1}" = " " ]; then 
		ssid="[unknown]"
		bssid=`echo $line | awk '{print $2}'`
		security=`echo $line | awk '{print $3}'`
		signal=`echo $line | awk '{print $4}'`
		wmode=`echo $line | awk '{print $5}'`
		extch=`echo $line | awk '{print $6}'`
		nt=`echo $line | awk '{print $7}'`
		wps=`echo $line | awk '{print $8}'`
	else
		ssid=`echo "${line:4:33}" | sed 's/[[:space:]]*$//'`
		ss=`uci show apcli0 | grep ssid | awk -F "=" '{print $2}'| grep "$ssid" 2>/dev/null`
		bssid=${line:37:17}
		security=`echo ${line:57} | awk '{print $1}'`
		signal=`echo ${line:57} | awk '{print $2}'`
		wmode=`echo ${line:57} | awk '{print $3}'`
		extch=`echo ${line:57} | awk '{print $4}'`
		nt=`echo ${line:57} | awk '{print $5}'`
		wps=`echo ${line:57} | awk '{print $6}'`
	fi

	if [ $i -ne 0 ]; then
	echo ","
	fi
	let i+=1

	echo "\"$ssid\":{"
	if [ "$ss"x = x ]; then
		echo "\"store\":"\"no\"","
	else
		echo "\"store\":"\"yes\"","
		ss=''
	fi
	echo "\"chanel\":"$chanel","
	echo "\"ssid\":\""$ssid"\","
	echo "\"bssid\":\""$bssid"\","
	echo "\"security\":\""$security"\","
	echo "\"signal\":\""$signal"\","
	echo "\"wmode\":\""$wmode"\","
	echo "\"extch\":\""$extch"\","
	echo "\"nt\":\""$nt"\","
	echo "\"wps\":\""$wps"\""
	echo -n "}"
done
echo "}"
