#!/bin/sh
#We don't understand the license things, so let it go.
#Please don't do evil to us.
#v2015-1-10 qizha/wangke/noel/summer

echo "Content-Type: application/json"
echo ""
apcli=`ifconfig | grep apcli0`
while [[ -z "$apcli" ]]
do
    apcli=`ifconfig | grep apcli0`
done

ip=`ifconfig apcli0 | grep 'inet addr:'| cut -d: -f2 | awk '{ print $1}'`
if [ $ip ]; then
    ap=`iwconfig | grep apcli0`
    ap=${ap#*\"}
    ap=${ap%\"*}
    echo "{\"result\":\"success\",\"message\":\"connected with IP $ip\",\"ip\":\"AP:$ap IP:$ip\"}"
else
    echo "{\"result\":\"error\",\"message\":\"can not connect to $ussid\"}"
fi
