#!/bin/sh
#We don't understand the license things, so let it go.
#Please don't do evil to us.
#v2015-1-10 qizha/wangke/noel/summer

echo "Content-Type: application/json"
echo ""
ssid=`uci get wireless.@wifi-iface[0].ssid`
if [ $ssid ]; then
    echo "{\"result\":\"success\",\"ssid\":\"$ssid\"}"
else
    echo "{\"result\":\"error\",\"message\":\"can not get ssid\"}"
fi
