#!/bin/sh /etc/rc.common

START=99


start(){
#	if [ ! -f /etc/.setpassword ] 
#	then
#		cd /etc && touch .setpassword && cd -
#		( echo ibeacon201506; echo ibeacon201506 ) | passwd >/dev/null 2>&1	
#	fi
	
	if [ ! -f /etc/.getSeials ] 
	then
		touch /etc/.getSeials
		cd /usr/ibeacon/bin/ && ./getSeials && cd -
	fi

	if [ ! -f /etc/.firstStart ] 
	then
		if [ ! -d /usr/rootdir ]
		then
			touch /etc/.firstStart
			cp -rfpP /usr/rootdir/* /
			rm -rf /usr/rootdir
		fi
	fi

	
	cd /usr/ibeacon/tool/ 
	./guardIbeacon.sh &
	cd -
}

